### ISSUE TITLE
Testar e anotar possíveis tratamento de erros 

### ISSUE THREAD

**Issue by luizfpq** [tsffarias/CPDCid-System#10]

**Comment by luizfpq** [comment]
Necessário tratar entradas no item 3 - Adicionar Carro


Traceback (most recent call last):
  File "/home/quirino/Documentos/CPDCid-System/./main.py", line 236, in <module>
    carro = carro_coleta_dados(placa)
  File "/home/quirino/Documentos/CPDCid-System/./main.py", line 56, in carro_coleta_dados
    raise Exception(f'Renavam inválido (padrão de 11 números não respeitados): {renavam}')
Exception: Renavam inválido (padrão de 11 números não respeitados): asdasd

**Comment by luizfpq** [comment]
Verificação das entradas no menu, digitar um valor inesperado não está tratado.

❐ Informe a sua opção (1 a 6): BMR7818
Traceback (most recent call last):
  File "/home/quirino/Documentos/CPDCid-System/./main.py", line 137, in <module>
    resposta_usuario = int(input('❐ Informe a sua opção (1 a 6): '))
ValueError: invalid literal for int() with base 10: 'BMR7818'

**Comment by luizfpq** [comment]
Entrar com uma placa não cadastrada, ou informada de maneira incorreta gera erro

❐ Informe a sua opção (1 a 6): 2
Digite a placa do carro a ser removido: BMR
Placa não existe.
Traceback (most recent call last):
  File "/home/quirino/Documentos/CPDCid-System/./main.py", line 225, in <module>
    start_time, end_time, 'Remoção de carro')
NameError: name 'start_time' is not defined

**Comment by edusatelis** [comment]
Ao tenta realizar a edição do carro na Arvore Binaria o mesmo me retorna um erro 

Digite a placa do carro: PZR2240
Traceback (most recent call last):
  File "/home/edusatelis/ED/CPDCid-System/main.py", line 266, in <module>
    carro = estrutura_de_dados.__getitem__(placa)
AttributeError: 'BinarySearchTree' object has no attribute '__getitem__'. Did you mean: '__setattr__'?
